# CMake generated Testfile for 
# Source directory: /home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/upf/test
# Build directory: /home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/upf/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(upf.levelshifter.tcl "/usr/bin/bash" "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/test/regression_test.sh")
set_tests_properties(upf.levelshifter.tcl PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/openroad;TEST_NAME=levelshifter;TEST_EXT=tcl;TEST_TYPE=tcl;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest tcl upf log_compare" WORKING_DIRECTORY "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/upf/test" _BACKTRACE_TRIPLES "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/cmake/testing.cmake;19;add_test;/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/cmake/testing.cmake;86;or_integration_test_single;/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/upf/test/CMakeLists.txt;1;or_integration_tests;/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/upf/test/CMakeLists.txt;0;")
add_test(upf.write.tcl "/usr/bin/bash" "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/test/regression_test.sh")
set_tests_properties(upf.write.tcl PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/openroad;TEST_NAME=write;TEST_EXT=tcl;TEST_TYPE=tcl;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest tcl upf log_compare" WORKING_DIRECTORY "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/upf/test" _BACKTRACE_TRIPLES "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/cmake/testing.cmake;19;add_test;/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/cmake/testing.cmake;86;or_integration_test_single;/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/upf/test/CMakeLists.txt;1;or_integration_tests;/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/upf/test/CMakeLists.txt;0;")
add_test(upf.isolation.tcl "/usr/bin/bash" "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/test/regression_test.sh")
set_tests_properties(upf.isolation.tcl PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/openroad;TEST_NAME=isolation;TEST_EXT=tcl;TEST_TYPE=tcl;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest tcl upf log_compare" WORKING_DIRECTORY "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/upf/test" _BACKTRACE_TRIPLES "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/cmake/testing.cmake;19;add_test;/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/cmake/testing.cmake;86;or_integration_test_single;/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/upf/test/CMakeLists.txt;1;or_integration_tests;/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/upf/test/CMakeLists.txt;0;")
add_test(upf.isolation_select.tcl "/usr/bin/bash" "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/test/regression_test.sh")
set_tests_properties(upf.isolation_select.tcl PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/openroad;TEST_NAME=isolation_select;TEST_EXT=tcl;TEST_TYPE=tcl;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest tcl upf log_compare" WORKING_DIRECTORY "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/upf/test" _BACKTRACE_TRIPLES "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/cmake/testing.cmake;19;add_test;/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/cmake/testing.cmake;86;or_integration_test_single;/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/upf/test/CMakeLists.txt;1;or_integration_tests;/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/upf/test/CMakeLists.txt;0;")
