if(EXISTS "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/dbSta/test/cpp/TestHconn[1]_tests.cmake")
  include("/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/dbSta/test/cpp/TestHconn[1]_tests.cmake")
else()
  add_test(TestHconn_NOT_BUILT TestHconn_NOT_BUILT)
endif()
