if(EXISTS "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/mpl/test/cpp/TestSnapper[1]_tests.cmake")
  include("/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/mpl/test/cpp/TestSnapper[1]_tests.cmake")
else()
  add_test(TestSnapper_NOT_BUILT TestSnapper_NOT_BUILT)
endif()
