if(EXISTS "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/gpl/test/fft_test[1]_tests.cmake")
  include("/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/gpl/test/fft_test[1]_tests.cmake")
else()
  add_test(fft_test_NOT_BUILT fft_test_NOT_BUILT)
endif()
