if(EXISTS "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/rmp/test/cpp/RmpGTests[1]_tests.cmake")
  include("/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/rmp/test/cpp/RmpGTests[1]_tests.cmake")
else()
  add_test(RmpGTests_NOT_BUILT RmpGTests_NOT_BUILT)
endif()
