if(EXISTS "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/rsz/test/cpp/TestBufRem1[1]_tests.cmake")
  include("/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/rsz/test/cpp/TestBufRem1[1]_tests.cmake")
else()
  add_test(TestBufRem1_NOT_BUILT TestBufRem1_NOT_BUILT)
endif()
