if(EXISTS "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/dft/test/cpp/TestScanArchitectHeuristic[1]_tests.cmake")
  include("/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/dft/test/cpp/TestScanArchitectHeuristic[1]_tests.cmake")
else()
  add_test(TestScanArchitectHeuristic_NOT_BUILT TestScanArchitectHeuristic_NOT_BUILT)
endif()
