# CMake generated Testfile for 
# Source directory: /home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/fin/test
# Build directory: /home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/fin/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(fin.gcd_fill.tcl "/usr/bin/bash" "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/test/regression_test.sh")
set_tests_properties(fin.gcd_fill.tcl PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/openroad;TEST_NAME=gcd_fill;TEST_EXT=tcl;TEST_TYPE=tcl;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest tcl fin log_compare" WORKING_DIRECTORY "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/fin/test" _BACKTRACE_TRIPLES "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/cmake/testing.cmake;19;add_test;/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/cmake/testing.cmake;86;or_integration_test_single;/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/fin/test/CMakeLists.txt;1;or_integration_tests;/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/fin/test/CMakeLists.txt;0;")
add_test(fin.gcd_fill.py "/usr/bin/bash" "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/test/regression_test.sh")
set_tests_properties(fin.gcd_fill.py PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/openroad;TEST_NAME=gcd_fill;TEST_EXT=py;TEST_TYPE=python;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest python fin log_compare" WORKING_DIRECTORY "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/fin/test" _BACKTRACE_TRIPLES "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/cmake/testing.cmake;19;add_test;/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/cmake/testing.cmake;88;or_integration_test_single;/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/fin/test/CMakeLists.txt;1;or_integration_tests;/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/src/fin/test/CMakeLists.txt;0;")
