if(EXISTS "/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/utl/test/cpp/TestCFileUtils[1]_tests.cmake")
  include("/home/fetzfs_projects/SAITPlacement/bodhi/SAIT-2D-Placer-v2/OpenROAD/build_test_sa2d/src/utl/test/cpp/TestCFileUtils[1]_tests.cmake")
else()
  add_test(TestCFileUtils_NOT_BUILT TestCFileUtils_NOT_BUILT)
endif()
